### ISSUE TITLE
Ikea items not loading.

### ISSUE THREAD

**Issue by KayceeT2** [giovannipds/xcode-ikea#1]
Hello! I downloaded your app, and ran it. When I run your app, every time I click on an item, and then click on the screen, nothing pops up. I've clicked many times, and nothing still pops up. Do you think you can fix that?

**Comment by giovannipds** [comment]
Hi there! Nice. Well, I'm really sorry but I currently have no Mac here to perform that for you. If you look at the description, this repo was an exercise result of an Udemy course. If you'd like, you can try buying it but I guarantee you they'll only help you get exactly where this code has gotten.

I'll also archive this repo since it's not a maintained app and it's only here for educational purposes.

But of course, if you'd like to maintain it, I can also merge a fix if you make it or you can just fork the project to continue it and I'll archive it from here. My best regards!

**Comment by KayceeT2** [comment]
Thank you. I will check out the course. I will let you know if I need your help.
